# Generated by Django 3.2.6 on 2021-11-20 13:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movie_number', models.CharField(max_length=100, unique=True)),
                ('title', models.CharField(max_length=50, unique=True)),
                ('sub_title', models.TextField()),
                ('poster', models.ImageField(upload_to='Posters/')),
                ('active_on_display', models.BooleanField(default=False, unique=True)),
                ('movie_info', models.TextField()),
                ('movie_item', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='User_Subscribers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=15)),
                ('last_name', models.CharField(max_length=15)),
                ('email', models.CharField(max_length=100)),
                ('phone_number', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Trailer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trailer_title', models.TextField()),
                ('trailer_item', models.TextField()),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='boomrok_app.movie')),
            ],
        ),
        migrations.AddField(
            model_name='movie',
            name='subscribers',
            field=models.ManyToManyField(to='boomrok_app.User_Subscribers'),
        ),
        migrations.CreateModel(
            name='Cast_Members',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='Cast_Members/')),
                ('first_name', models.CharField(max_length=25)),
                ('last_name', models.CharField(max_length=25)),
                ('screen_name', models.CharField(max_length=35)),
                ('role', models.TextField()),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='boomrok_app.movie')),
            ],
        ),
    ]
