# Generated by Django 3.2.6 on 2021-11-22 09:25

import django.core.validators
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('boomrok_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='active_on_display',
        ),
        migrations.AddField(
            model_name='movie',
            name='date_posted',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='movie',
            name='release_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='trailer',
            name='active_on_display',
            field=models.BooleanField(default=False, unique=True),
        ),
        migrations.AddField(
            model_name='trailer',
            name='date_posted',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='cast_members',
            name='image',
            field=models.ImageField(upload_to='Files/Cast_Members/'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='movie_item',
            field=models.FileField(upload_to='Files/Movies/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['mp4'])]),
        ),
        migrations.AlterField(
            model_name='movie',
            name='poster',
            field=models.ImageField(upload_to='Files/Posters/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'png', 'jpeg'])]),
        ),
        migrations.AlterField(
            model_name='trailer',
            name='trailer_item',
            field=models.FileField(upload_to='Files/Trailers/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['mp4'])]),
        ),
        migrations.AlterField(
            model_name='user_subscribers',
            name='first_name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='user_subscribers',
            name='last_name',
            field=models.CharField(max_length=50),
        ),
    ]
