# Generated by Django 3.2.6 on 2021-11-22 10:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('boomrok_app', '0002_auto_20211122_1225'),
    ]

    operations = [
        migrations.AddField(
            model_name='trailer',
            name='trailer_description',
            field=models.TextField(default='trailer description'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='trailer',
            name='movie',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='boomrok_app.movie'),
        ),
        migrations.AlterField(
            model_name='trailer',
            name='trailer_title',
            field=models.CharField(max_length=100),
        ),
    ]
