# Generated by Django 3.2.6 on 2021-11-22 14:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('boomrok_app', '0003_auto_20211122_1304'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trailer',
            name='trailer_description',
        ),
    ]
