# Generated by Django 3.2.6 on 2021-11-23 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boomrok_app', '0005_trailer_trailer_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='directors',
            field=models.TextField(default='Directors go Here, separate with commas'),
        ),
        migrations.AddField(
            model_name='movie',
            name='writers',
            field=models.TextField(default='Writers Go hera, separate with commas'),
        ),
    ]
