# Generated by Django 3.2.6 on 2021-11-23 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boomrok_app', '0006_auto_20211123_1109'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='category',
            field=models.CharField(default='Category Goes here', max_length=100),
        ),
    ]
