# Generated by Django 3.2.6 on 2021-11-26 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boomrok_app', '0007_movie_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='pg_rating',
            field=models.CharField(default='PG-13', max_length=10),
        ),
    ]
